name: Build FFmpeg for Windows

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-ffmpeg:
    name: Build FFmpeg
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; `
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install dependencies
        run: choco install -y yasm nasm cmake git perl

      - name: Clone WebRTC repository
        run: |
          git clone https://chromium.googlesource.com/external/webrtc.git webrtc

      - name: Build WebRTC
        working-directory: ./webrtc
        run: |
          gclient sync --with_branch_heads --with_tags
          gn gen out/Release "--args=is_debug=false is_component_build=false rtc_include_tests=false use_rtti=true"
          ninja -C out/Release

      - name: Clone FFmpeg repository
        run: |
          git clone https://github.com/FFmpeg/FFmpeg.git ffmpeg

      - name: Configure FFmpeg
        working-directory: ./ffmpeg
        run: |
          PKG_CONFIG_PATH="./webrtc/src/out/Release/lib/pkgconfig" ./configure --enable-gpl --enable-nonfree --enable-libvpx --enable-libaom --enable-libopus --enable-libvorbis --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libdav1d --enable-openssl --enable-libwebp --enable-libzimg --enable-libsvtav1 --enable-libopenh264 --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libass --enable-libbluray --enable-libdrm --enable-libmysofa --enable-libopenjpeg --enable-libxml2 --enable-lzma --enable-zlib --enable-runtime-cpudetect --enable-pthreads --enable-static --disable-shared

      - name: Build FFmpeg
        working-directory: ./ffmpeg
        run: make -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: ffmpeg-windows
          path: ./ffmpeg
