name: Build FFmpeg with WebRTC support for Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup MSYS2 environment
        uses: msys2/setup-msys2@v2
        with:
          update: true

      - name: Install dependencies
        run: |
          pacman -S --needed --noconfirm \
            git make pkg-config diffutils wget tar yasm \
            mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2 \
            mingw-w64-x86_64-ffmpeg mingw-w64-x86_64-openssl \
            mingw-w64-x86_64-libwebp mingw-w64-x86_64-mpg123 \
            mingw-w64-x86_64-x264 mingw-w64-x86_64-x265 \
            mingw-w64-x86_64-libbluray mingw-w64-x86_64-libvpx \
            mingw-w64-x86_64-libass mingw-w64-x86_64-libxml2 \
            mingw-w64-x86_64-libiconv mingw-w64-x86_64-libvorbis \
            mingw-w64-x86_64-libopus mingw-w64-x86_64-faad2 \
            python python-pip unzip curl ninja cmake
          pip install meson

      - name: Clone FFmpeg and WebRTC repositories
        run: |
          git clone https://github.com/FFmpeg/FFmpeg.git
          git clone https://chromium.googlesource.com/external/webrtc.git

      - name: Apply patches for WebRTC support
        run: |
          cd FFmpeg && \
          patch -p1 < ../webrtc/patches/ffmpeg.patch && \
          patch -p1 < ../webrtc/patches/libavutil/float_dsp.patch && \
          patch -p1 < ../webrtc/patches/libavcodec/omx.c.patch

      - name: Configure FFmpeg with WebRTC support
        run: |
          cd FFmpeg && \
          PKG_CONFIG_PATH=/mingw64/lib/pkgconfig \
          ./configure --pkg-config-flags="--static" \
          --toolchain=msvc --arch=x86_64 --enable-gpl \
          --enable-version3 --enable-shared --disable-static \
          --enable-libopencore-amrnb --enable-libopencore-amrwb \
          --enable-libvpx --enable-libopus --enable-libvorbis \
          --enable-libmp3lame --enable-libx264 --enable-libx265 \
          --enable-nonfree --enable-decklink --enable-nvenc \
          --enable-d3d11va --enable-dxva2 --enable-libmfx \
          --enable-openssl --enable-libmysofa --enable-libzimg \
          --enable-libgsm --enable-libaom --enable-libsvtav1 \
          --enable-libdav1d --enable-libopenjpeg \
          --enable-libaribb24 --enable-libbluray --enable-libfreetype \
          --enable-libass --enable-libzvbi --enable-libcaca \
          --enable-libflite --enable-libvmaf --enable-webrtc

      - name: Build FFmpeg with WebRTC support
        run: |
          cd FFmpeg && \
          make -j$(nproc)

      - name: Check FFmpeg build
        run: |
          cd FFmpeg && \
          make check

      - name: Validate FFmpeg binaries
        run: |
          cd FFmpeg && \
          make tools/qt-faststart && \
          ./tools/qt-faststart.exe -h
