name: Build FFmpeg for windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ffmpeg:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Git, Python and Ninja
      run: |
        choco install -y git python ninja

    - name: Clone FFmpeg source code
      run: |
        git clone https://github.com/FFmpeg/FFmpeg.git ffmpeg
        cd ffmpeg
        git checkout master

    - name: Configure FFmpeg with WebRTC support
      run: |
        python ./configure --enable-gpl --enable-version3 --enable-nonfree --enable-shared --enable-static --enable-libvorbis --enable-libopus --enable-libmp3lame --enable-libfdk-aac --enable-libx264 --enable-libx265 --enable-libvpx --enable-libaom --enable-libdav1d --enable-libwebp --enable-libsvtav1 --enable-libsrt --enable-libxml2 --enable-libzimg --enable-libbluray --disable-debug --extra-cflags=-w --extra-ldflags=-mwindows --enable-openssl --enable-webrtc --enable-nvenc --enable-cuda

    - name: Build FFmpeg with Ninja
      run: |
        ninja -C ./ffmpeg/build

    - name: Upload FFmpeg binaries to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: ffmpeg
        path: ./ffmpeg/build
