name: Build FFmpeg with WebRTC support and upload artifact

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      # Install dependencies
      - name: Install dependencies
        run: |
          choco install nasm
          choco install python --version=3.9.0
          choco install strawberryperl
          
          set PYTHON=C:\Python39\python.exe
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          set PATH=%PATH%;C:\path\to\depot_tools
          gclient
          ninja -C out/Release webrtc

      # Build FFmpeg with WebRTC support
      - name: Build FFmpeg with WebRTC support
        run: |
          cd ffmpeg
          ./configure --enable-gpl --enable-libx264 --enable-libfdk-aac --enable-libwebp --enable-libopus --enable-libvpx --extra-cflags="-I../webrtc/src" --extra-ldflags="-L../webrtc/src/out/Release/obj" --enable-librav1e --enable-libsvtav1 --enable-libdav1d --enable-libaom --enable-decklink
          make

      # Create Windows executable
      - name: Create Windows executable
        run: |
          cd ffmpeg
          make install
          zip -r ffmpeg.zip bin/

      # Upload the FFmpeg executable
      - name: Upload FFmpeg executable
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-windows-x64.zip # Artifact name
          path: ffmpeg/ffmpeg.zip # File path to upload
