name: Build FFmpeg For Win

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ffmpeg:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MSYS2
      shell: powershell
      run: |
        Invoke-WebRequest -Uri https://github.com/msys2/msys2-installer/releases/download/2021-06-28/msys2-x86_64-20210628.exe -OutFile msys2.exe
        Start-Process .\msys2.exe -ArgumentList '/S' -Wait
        rm .\msys2.exe

    - name: Install dependencies
      shell: bash
      run: |
        pacman --noconfirm -Syu
        pacman --noconfirm -S git make mingw-w64-x86_64-toolchain mingw-w64-x86_64-nasm python3 yasm mercurial

    - name: Set environment variables
      shell: bash
      run: |
        export LC_ALL=C.UTF-8
        export PATH=/mingw64/bin:$PATH

    - name: Clone FFmpeg repository
      run: hg clone https://hg.ffmpeg.org/ffmpeg ffmpeg

    - name: Configure FFmpeg with all features and WebRTC support
      shell: bash
      working-directory: ./ffmpeg
      run: |
        ./configure --enable-gpl --enable-version3 --enable-nonfree --enable-shared --enable-static --enable-openssl --enable-libsrt --enable-libzmq --enable-libx264 --enable-libx265 --enable-libvpx --enable-libaom --enable-libsvtav1 --enable-libdav1d --enable-librav1e --enable-pthreads --enable-runtime-cpudetect --enable-vaapi --enable-vdpau --enable-cuda-nvcc --enable-cuvid --enable-libnpp --enable-libmfx --enable-libdrm --enable-opencl --enable-amf --enable-frei0r --enable-libass --enable-libfreetype --enable-libfontconfig --enable-libfribidi --enable-libbluray --enable-libopenh264 --enable-libopenjpeg --enable-libwebp --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libspeex --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libgsm --enable-libilbc --enable-libvo-amrwbenc --enable-libwavpack --enable-libtwolame --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopusenc --enable-libsnappy --enable-libsoxr --enable-libssh --enable-libtesseract --enable-libvidstab --enable-librubberband --enable-libzimg --enable-libzvbi --enable-lv2 --enable-sdl2 --enable-zlib --enable-webrtc

    - name: Compile FFmpeg
      shell: bash
      working-directory: ./ffmpeg
      run: |
        make -j4 && make install

    - name: Upload FFmpeg artifacts to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: ffmpeg-build
        path: ${{ github.workspace }}/ffmpeg
